version: "3.8"

services:
  health-tracker-webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: health-tracker-webapp
    container_name: health-tracker-webapp
    command: "npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app

      # create an empty directory at `/app/node_modules` instead of using the previously
      # mounted `./webapp/node_modules` directory, so the host's `node_modules` ownership
      # doesn't pass to the container's user
      - /app/node_modules
    # depends_on:
    #   - health-tracker-api

  health-tracker-api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: release
    image: health-tracker-api
    container_name: health-tracker-api
    ports:
      - "3001:3001"
    environment:
      - API_PORT=${API_PORT:-3001}
      - DATABASE_URL=/api/local.sqlite
      - API_HOSTNAME=http://0.0.0.0:${API_PORT:-3001}
      - API_TOKEN=${API_TOKEN}
      - ENABLE_SWAGGER_UI=true
      - RUST_LOG=${RUST_LOG:-info}
    volumes:
      - ./api/local.sqlite:/api/local.sqlite

  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "1234"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
