#!/usr/bin/env bash

#
#   Copy remote SQLite DB to local
#

set -o nounset
set -o pipefail
set -o errexit

info () {
    message="[INFO] ${1}"
    echo >&2 "${message}"
}

REMOTE_FILE_NAME='health-tracker-api-db.sqlite'
stem="$( echo "${REMOTE_FILE_NAME}" | sed -E 's/\.sqlite//g' )"

timestamp="$( \
    date --rfc-3339='seconds' --utc `# 2024-05-18 11:06:45+00:00` \
    | sed -E 's/\+00:00//g' \
    | sed -E 's/-//g' \
    | sed -E 's/://g' \
    | sed -E 's/ /-/g'
)"
file_name="${stem}-backup-${timestamp}.sqlite"
vps_data_dir="/home/${VPS_USER}/k3s-data"

info "downloading ${REMOTE_FILE_NAME}"
scp "${VPS_HOSTNAME}@${VPS_USER}:${vps_data_dir}/${REMOTE_FILE_NAME}" "${file_name}"
info "backup stored at $(realpath "${file_name}" )"
